### ISSUE TITLE
NoClassDefFoundError after update

### ISSUE THREAD

**Issue by TPeterW** [afollestad/material-dialogs#970]
After I updated to 0.8.5.5, it reports this error when I run the app:

    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;

**Comment by afollestad** [comment]
Unable to reproduce. No problems in the sample project or any of my apps.

**Comment by fahimk** [comment]
@afollestad seeing this same issue, will try and debug

**Comment by mfietz** [comment]
We get similar reports. So far only from people running CyanogenMod (12.x and 13.x).

**Comment by mfietz** [comment]
We are facing the same issue. We are currently using version 0.8.5.3
During building, I noticed that this version now seems to depend on support 23.2.0 instead of 23.1.1 as it is supposed to.
Just checked the jitpack build logs and it looks like that something really went wrong there: https://jitpack.io/com/github/afollestad/material-dialogs/0.8.5.3/build.log

Seems updating to support 23.2.0 solves the issue, though.
