### ISSUE TITLE
progressbar indeterminateprogressdrawable error in 0.9.0.2 in 4.4 kitkat working in 6.0 marshmallow

### ISSUE THREAD

**Issue by pravinbadgujar** [afollestad/material-dialogs#1209]
java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable

**Comment by pravinbadgujar** [comment]
java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable
                                                                                at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:369)
                                                                                at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:297)
                                                                                at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
                                                                                at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1311)
                                                                                at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1316)
                                                                                at com.sassyinfotech.Ricobook.Rico.Login.submitForm(Login.java:175)
                                                                                at com.sassyinfotech.Ricobook.Rico.Login.access$100(Login.java:49)
                                                                                at com.sassyinfotech.Ricobook.Rico.Login$4.onEditorAction(Login.java:124)
                                                                                at android.widget.TextView.onEditorAction(TextView.java:4243)
                                                                                at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
                                                                                at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
                                                                                at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by afollestad** [comment]
https://github.com/DreaminginCodeZH/MaterialProgressBar
